version: 2.1

orbs:
  torque: quali/torque@1.0.0
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - torque/start-sandbox:
          sandbox-name: "circleci-test"
          blueprint: "promotions-manager-all-aws-dev"
          inputs: "{'AWS_INSTANCE_TYPE': 'm5.large'}"
          artifacts: "{'promotions-manager-ui':'artifacts/latest/promotions-manager-ui.master.tar.gz','promotions-manager-api':'artifacts/latest/promotions-manager-api.master.tar.gz', 'mongodb': 'artifacts/test-data/test-data-db.tar' }"
      - run:
          name: Functional test
          command: |
            SB_ENDPOINT="SB_${SANDBOX_ID}_SHORTCUT_1"
            echo "Checking ${!SB_ENDPOINT}"
            PAYLOAD='{"firstname":"Lead","lastname":"Easy","company":"Quali","phone":"123456789"}'
            for i in {1..10}
            do
              curl --silent -X POST ${!SB_ENDPOINT}/api/leads -d $PAYLOAD \
                   -H "accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" > /dev/null
              sleep 5
            done
            NUM=`curl --silent -X GET ${!SB_ENDPOINT}/api/leads | grep -o Easy | wc -l` || exit 1
            [[ $NUM > 2 ]]
      - torque/end-sandbox:
          sandbox-id: SANDBOX_ID
workflows:
  testpromotionmanager:
    jobs:
      - test